require("weapp-adapter.js");
//
require("libs/laya.core.js");
//
require("libs/laya.webgl_2D.js");
//
require("libs/laya.d3.js");
//
require("libs/laya.webgl_3D.js");
//
require("libs/laya.ui.js");
//
require("libs/laya.ani.js");
//
require("libs/laya.wxmini.js");
//

//
require("js/bundle.js");
//
require("js/index.js");