/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * change_text.ls
 */
export class change_textBase extends Laya.Scene {
    public Ltitle!: Laya.Label;
    public Tdata!: Laya.TextArea;
    public Bclose!: Laya.Button;
    public Bcommit!: Laya.Button;
    public Bhtml!: Laya.Button;
}

