/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/dialog.lh
 */
export class dialogBase extends Laya.Dialog {
    public maintext!: Laya.Label;
}

