/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * hello.ls
 */
export class helloBase extends Laya.Scene {
    public search_input!: Laya.TextInput;
    public Bsearch!: Laya.Button;
    public Blogin!: Laya.Button;
    public selectBox1!: Laya.ComboBox;
    public selectBox2!: Laya.ComboBox;
    public HBox1!: Laya.HBox;
    public Iteacher1!: Laya.Image;
    public Lteacher1!: Laya.Label;
    public Iteacher2!: Laya.Image;
    public Lteacher2!: Laya.Label;
    public Iteacher3!: Laya.Image;
    public Lteacher3!: Laya.Label;
    public Iteacher4!: Laya.Image;
    public Lteacher4!: Laya.Label;
    public HBox2!: Laya.HBox;
    public Iteacher5!: Laya.Image;
    public Lteacher5!: Laya.Label;
    public Iteacher6!: Laya.Image;
    public Lteacher6!: Laya.Label;
    public Iteacher7!: Laya.Image;
    public Lteacher7!: Laya.Label;
    public Iteacher8!: Laya.Image;
    public Lteacher8!: Laya.Label;
}

