/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * search_list.ls
 */
export class search_listBase extends Laya.Scene {
    public List!: Laya.List;
    public search_input!: Laya.TextInput;
    public Bsearch!: Laya.Button;
    public selectBox1!: Laya.ComboBox;
}

