/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * teacher_base.ls
 */
export class teacher_baseBase extends Laya.Scene {
    public Iphoto!: Laya.Image;
    public Lname!: Laya.Label;
    public Lbelong!: Laya.Label;
    public Bgoback!: Laya.Button;
    public Bselect1!: Laya.Button;
    public Bselect2!: Laya.Button;
    public Bselect3!: Laya.Button;
    public Bselect4!: Laya.Button;
    public ViewStack!: Laya.ViewStack;
    public Bchange!: Laya.Button;
    public LTupdate!: Laya.Label;
    public Lintro!: Laya.Label;
    //public Bchange!: Laya.Button;
    public Lhonor!: Laya.Label;
    //public Bchange!: Laya.Button;
    public Ledu!: Laya.Label;
    //public Bchange!: Laya.Button;
    public Ldateupdate!: Laya.Label;
    public Ldate1!: Laya.Label;
    //public Bchange!: Laya.Button;
    public Ldate2!: Laya.Label;
    //public Bchange!: Laya.Button;
    public Lsciupdate!: Laya.Label;
    public Lsci1!: Laya.Label;
    //public Bchange!: Laya.Button;
    public Lsci2!: Laya.Label;
    //public Bchange!: Laya.Button;
    public Lsci3!: Laya.Label;
    //public Bchange!: Laya.Button;
    public Lenrollupdate!: Laya.Label;
    public Lenroll1!: Laya.Label;
    //public Bchange!: Laya.Button;
    public Lenroll2!: Laya.Label;
    //public Bchange!: Laya.Button;
    public Lenroll3!: Laya.Label;
}

