/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * date.ls
 */
export class dateBase extends Laya.Scene {
    public Tdata!: Laya.TextArea;
    public time!: Laya.TextInput;
    public location!: Laya.TextInput;
    public email!: Laya.TextInput;
    public code!: Laya.TextInput;
    public Bsendcode!: Laya.Button;
    public Bevaluate!: Laya.Button;
    public Bcommite!: Laya.Button;
    public Bgoback!: Laya.Button;
}

