/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * date_details.ls
 */
export class date_detailsBase extends Laya.Scene {
    public time!: Laya.TextInput;
    public location!: Laya.TextInput;
    public email!: Laya.TextInput;
    public description!: Laya.TextInput;
    public Treply!: Laya.TextArea;
    public Bagree!: Laya.Button;
    public Brefuse!: Laya.Button;
    public Bchange!: Laya.Button;
    public Bfinish!: Laya.Button;
    public Bgoback!: Laya.Button;
    public Iwait!: Laya.Image;
}

