/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * date_list.ls
 */
export class date_listBase extends Laya.Scene {
    public List!: Laya.List;
}

