/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * hello.ls
 */
export class helloBase extends Laya.Scene {
    public search_input!: Laya.TextInput;
    public Bsearch!: Laya.Button;
    public Blogin!: Laya.Button;
    public Iteacher1!: Laya.Image;
    public Iteacher2!: Laya.Image;
    public Iteacher3!: Laya.Image;
    public Iteacher4!: Laya.Image;
    public Iteacher5!: Laya.Image;
    public Iteacher6!: Laya.Image;
    public Iteacher7!: Laya.Image;
    public Iteacher8!: Laya.Image;
}

