/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * login.ls
 */
export class loginBase extends Laya.Scene {
    public Tusername!: Laya.TextInput;
    public Tpassword!: Laya.TextInput;
    public Blogin!: Laya.Button;
}

